server: true
markdown: rdiscount
rdiscount:
  extensions: [smart]
baseurl: /clean-blog
production_url : http://username.github.com/
permalink: :title
prose:
  siteurl: "http://www.youngist.github.io/clean-blog/"
